### ISSUE TITLE
 hsl2rgb(hue, sat, lum, rgb);

### ISSUE THREAD

**Issue by agent99s** [lewisd32/CampFire#1]
I'm new to electronics, coding, and this site.  I wanted to try the code but I keep getting an error that I don't understand.  What am I missing?  It's confusing since it's declared at the top of the code,
 #include     <hsl2rgb.h>.  Is there a separate library I need?   

CampFire.ino: In function 'void loop()':
CampFire:121: error: 'hsl2rgb' was not declared in this scope

**Comment by lewisd32** [comment]
I should probably add this to the documentation.  Yes, there is another library you'll need.
https://github.com/lewisd32/avr-hsl2rgb
It deals with converting "hue, saturation, luminance" colour values to the "red, green, blue" that the LEDs use.

**Comment by agent99s** [comment]
AH HA!!!! That did the trick! Thank you! I thought I was going crazy.  Appreciate it! 
Thank you, Kathleen 

Date: Fri, 6 Feb 2015 11:30:15 -0800
